<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>DLH.Controls.Wpf</PackageId>
    <Version>0.2.0-preview.3</Version>
    <Authors>Leonardo D. de L. Hessel</Authors>
    <Description>Componentes WPF customizáveis, incluindo TabControl com superfície contínua e DataGridView com seleção, ordenação e colunas configuráveis.</Description>
    <PackageTags>WPF;Controls;TabControl;DataGrid;DataGridView;Windows;Paket</PackageTags>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <Copyright>Copyright © 2026 Leonardo D. de L. Hessel</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/LeonardoHessel/DLH.Controls</PackageProjectUrl>
    <RepositoryUrl>https://github.com/LeonardoHessel/DLH.Controls.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <IsPackable>true</IsPackable>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup><None Include="..\..\README.md" Pack="true" PackagePath="\" /><None Include="..\..\LICENSE.txt" Pack="true" PackagePath="\" /></ItemGroup>
</Project>
