<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>DLH.Controls.Wpf</PackageId>
    <Version>0.1.0-preview.3</Version>
    <Authors>Leonardo D. de L. Hessel</Authors>
    <Description>DLH Controls: componentes WPF customizáveis. Inclui TabControl com superfície contínua, reordenação e configurações.</Description>
    <PackageTags>WPF;Controls;TabControl;Windows</PackageTags>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <Copyright>Copyright © 2026 Leonardo D. de L. Hessel</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>true</IsPackable>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup><None Include="..\..\README.md" Pack="true" PackagePath="\" /><None Include="..\..\LICENSE.txt" Pack="true" PackagePath="\" /></ItemGroup>
</Project>
